# M0 · 01 — Tensor basics

A **tensor** is just an n-dimensional array of numbers (like a NumPy array) that
PyTorch can run fast and differentiate. Scalars, vectors, matrices, and the
`(batch, time, channel)` blocks in the GPT are *all* tensors — they only differ
in **how many dimensions** they have.

How these notebooks work: each exercise has a `TODO` you replace with your code,
then run the `check(...)` cell right below it. Green ✅ = correct.

> Tip: run the setup cell first (Shift+Enter), then work top to bottom.

In [1]:
import torch
from m0_checks import check, check_tensor, TODO
torch.manual_seed(0)

## 1. Make a tensor from a Python list

`torch.tensor([...])` turns ordinary Python numbers into a tensor.
Create the vector `[1, 2, 3]`.

In [2]:
v = torch.tensor([1,2,3])
v

tensor([1, 2, 3])

In [3]:
check('vector from list', v, torch.tensor([1, 2, 3]))

✅ vector from list


True

## 2. Dimensions (rank): 0-D, 1-D, 2-D

The number of axes is the tensor's **rank** (`.ndim`).
- scalar `torch.tensor(5)` → 0-D
- vector `[5]` → 1-D
- matrix `[[5]]` → 2-D

Build a **2-D** tensor (a 2×3 matrix) with rows `[1,2,3]` and `[4,5,6]`.

In [4]:
m = torch.tensor([[1,2,3], [4,5,6]])   # a list of lists
m

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
check('matrix values', m, torch.tensor([[1, 2, 3], [4, 5, 6]]))
check('matrix is 2-D', m.ndim if m is not TODO else TODO, 2)

✅ matrix values
✅ matrix is 2-D


True

## 3. Shape

`.shape` tells you the size along each axis. For the 2×3 matrix above it is
`(2, 3)` — 2 rows, 3 columns. In the GPT you will read shapes constantly to
keep track of `(B, T, C)`.

Store the shape of `m` as a **tuple** in `m_shape`.

In [6]:
m_shape = tuple(m.shape)
m_shape

(2, 3)

In [7]:
check('shape is (2,3)', m_shape, (2, 3))

✅ shape is (2,3)


True

## 4. dtype (integer vs float)

Tensors have a **dtype**. Token IDs are integers (`torch.long`); model weights
and probabilities are floats (`torch.float32`). Mixing them up causes real bugs
later, so it is worth feeling the difference now.

Make a **float** tensor `[1.0, 2.0, 3.0]` — note the decimal points.

In [8]:
f = torch.tensor([1.0,2.0,3.0])
f.dtype

torch.float32

In [9]:
check_tensor('float dtype', f, dtype=torch.float32)

✅ float dtype


True

## 5. Handy constructors: zeros, ones, arange

You will use these all the time:
- `torch.zeros(n)` / `torch.ones(n)` → filled tensors
- `torch.arange(n)` → `[0, 1, ..., n-1]` (exactly how position indices are made
  in the GPT: `torch.arange(T)`)

Create `torch.arange` for the numbers 0..4 (five values).

In [10]:
r = torch.arange(5)
r

tensor([0, 1, 2, 3, 4])

In [11]:
check('arange 0..4', r, torch.tensor([0, 1, 2, 3, 4]))

✅ arange 0..4


True

## ✅ Recap

- A tensor = n-dimensional array; **rank** = number of axes (`.ndim`).
- `.shape` = size per axis; you'll track `(B, T, C)` with it.
- **dtype** matters: `long` for IDs, `float32` for weights/probabilities.
- `zeros` / `ones` / `arange` build tensors without typing literals.

Next: **02 — indexing & slicing** (the `[:T]`, `[-1]`, `[:, -1, :]` you saw in the GPT).